controllers:
<<<<<<< ours
  resource: ../src/Controller/
  type: attribute

kernel:
  resource: ../src/Kernel.php
  type: attribute
=======
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> theirs
